version: "3.5"

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - ./www:/code
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      php:
        condition: service_healthy
  php:
    image: ghcr.io/schreier-development/php-fpm-healthcheck:latest
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./www:/code

networks:
  backend:
    external: false
    driver: bridge
